export const imgMods = [
  /** Style */
  // 'Abstract',
  // 'Academic',
  // 'Action painting',
  // 'Aesthetic',
  // 'Angular',
  // 'Automatism',
  // 'Avant-garde',
  // 'Baroque',
  // 'Bauhaus',
  // 'Contemporary',
  // 'Cubism',
  // 'Cyberpunk',
  // 'Digital art',
  // 'photo',
  // 'vector art',
  // 'Expressionism',
  // 'Fantasy',
  // 'Impressionism',
  // 'kiyo-e',
  // 'Medieval',
  // 'Minimal',
  // 'Modern',
  // 'Pixel art',
  // 'Realism',
  // 'sci-fi',
  // 'Surrealism',
  // 'synthwave',
  // '3d-model',
  // 'analog-film',
  // 'anime',
  // 'comic-book',
  // 'enhance',
  // 'fantasy-art',
  // 'isometric',
  // 'line-art',
  // 'low-poly',
  // 'modeling-compound',
  // 'origami',
  // 'photographic',
  // 'tile-texture',

  /** Format */
  // '3D render',
  // 'Blender Model',
  // 'CGI rendering',
  'cinematic',
  // 'Detailed render',
  // 'oil painting',
  // 'unreal engine 5',
  // 'watercolor',
  // 'cartoon',
  // 'anime',
  // 'colored pencil'

  /** Quality */
  'high resolution',
  // 'high-detail',
  // 'low-poly',
  // 'photographic',
  // 'photorealistic',
  // 'realistic',

  /** Effects */
  // 'Beautiful lighting',
  // 'Cinematic lighting',
  // 'Dramatic',
  // 'dramatic lighting',
  // 'Dynamic lighting',
  'epic',
  // 'Portrait lighting',
  // 'Volumetric lighting',
];

export const fighters = [
  // Mythological
  'Zeus',
  'Hades',
  'Hercules',
  'Cerberus',
  'Bahamut',
  'A dragon',
  'A chimera',
  'A unicorn',
  'A centaur',
  'A basilisk',
  'A giant cyclops',
  // Cryptids
  'A chupacabra',
  'The Lock Ness Monster',
  'Big Foot',
  'A yeti',
  'Mothman',
  // Fantasy
  'A werewolf',
  'A vampire',
  'An elf',
  'An ogre',
  'A goblin',
  'A griffin',
  'A zombie',
  'A kraken',
  // Sci-fi
  'A ghost',
  'A demon',
  'An alien',
  'A shapeshifter',
  'A body-snatcher',
  'Cthulhu',
  // People
  'A pirate',
  'A ninja',
  'A samurai',
  'A knight',
  'A viking',
  'Sherlock Holmes',
  'Hercule Poirot',
  // Animals
  'A rabid squirrel',
  'A raccoon with a knife',
  'An angry mongoose',
  'A king cobra',
  'A komodo dragon',
  'A silverback gorilla',
  'A hippopotamus',
  'A lion, tiger, and bear',
];